### ISSUE TITLE
Install issues

### ISSUE THREAD

**Issue by AdamDonna** [furious-luke/pycrime#1]
Installing Pycrime has an issue related to the depdency baseapi

I tried to install baseapi separately but this didn't help

```
(venv) ➜  spence git:(feature/advisor_email_theft_risk) ✗ pip install pycrime
Collecting pycrime
  Using cached https://files.pythonhosted.org/packages/87/18/c50cc5cdd1ec8955155fe6f27d06bd8abbd18bd47d9c6488b49ffac4b340/pycrime-0.0.4.tar.gz
    ERROR: Command errored out with exit status 1:
     command: /Users/adam/projects/spence/venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/dp/f802hncn4_gb36nzszdjxfq00000gn/T/pip-install-3e13fz3s/pycrime/setup.py'"'"'; __file__='"'"'/private/var/folders/dp/f802hncn4_gb36nzszdjxfq00000gn/T/pip-install-3e13fz3s/pycrime/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/dp/f802hncn4_gb36nzszdjxfq00000gn/T/pip-install-3e13fz3s/pycrime/pip-egg-info
         cwd: /private/var/folders/dp/f802hncn4_gb36nzszdjxfq00000gn/T/pip-install-3e13fz3s/pycrime/
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/dp/f802hncn4_gb36nzszdjxfq00000gn/T/pip-install-3e13fz3s/pycrime/setup.py", line 3, in <module>
        from pycrime.__version__ import __version__
      File "/private/var/folders/dp/f802hncn4_gb36nzszdjxfq00000gn/T/pip-install-3e13fz3s/pycrime/pycrime/__init__.py", line 2, in <module>
        from .client import CrimeClient  # noqa
      File "/private/var/folders/dp/f802hncn4_gb36nzszdjxfq00000gn/T/pip-install-3e13fz3s/pycrime/pycrime/client.py", line 1, in <module>
        from baseapi import Client
    ModuleNotFoundError: No module named 'baseapi'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
WARNING: You are using pip version 19.3.1; however, version 20.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

**Comment by furious-luke** [comment]
Hey @AdamDonna! Ah, I thought I'd fixed this issue but seemingly I've not done so at all. The issue surround importing the current package version from a single location such that it's both available as the PyPI version and from within the package itself. I'll fix this now and post again once it's done.

**Comment by furious-luke** [comment]
Just released v0.0.5 to fix this issue and tested locally. I'm going to close it now, please reopen if the issue persists for you.

**Comment by AdamDonna** [comment]
Looks like a similar error but with requests, which is a dependency of BaseAPI. I'm happy to leave this package and go directly to the API if I can source a JWT from you, then revisit using this package later 👍 

```
    ERROR: Command errored out with exit status 1:
     command: /Users/adamdonaghy/Projects/Work/expensecheck/spence/venv/bin/python3.6 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/r_/zld3tvk55kzgw3dw1twhd71c0000gn/T/pip-install-kid3mp55/base-api/setup.py'"'"'; __file__='"'"'/private/var/folders/r_/zld3tvk55kzgw3dw1twhd71c0000gn/T/pip-install-kid3mp55/base-api/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/r_/zld3tvk55kzgw3dw1twhd71c0000gn/T/pip-install-kid3mp55/base-api/pip-egg-info
         cwd: /private/var/folders/r_/zld3tvk55kzgw3dw1twhd71c0000gn/T/pip-install-kid3mp55/base-api/
    Complete output (13 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/r_/zld3tvk55kzgw3dw1twhd71c0000gn/T/pip-install-kid3mp55/base-api/setup.py", line 2, in <module>
        from baseapi import __version__
      File "/private/var/folders/r_/zld3tvk55kzgw3dw1twhd71c0000gn/T/pip-install-kid3mp55/base-api/baseapi/__init__.py", line 1, in <module>
        from .client import Client  # noqa
      File "/private/var/folders/r_/zld3tvk55kzgw3dw1twhd71c0000gn/T/pip-install-kid3mp55/base-api/baseapi/client.py", line 3, in <module>
        from .apis import Api
      File "/private/var/folders/r_/zld3tvk55kzgw3dw1twhd71c0000gn/T/pip-install-kid3mp55/base-api/baseapi/apis/__init__.py", line 2, in <module>
        from .graphql import GraphqlApi  # noqa
      File "/private/var/folders/r_/zld3tvk55kzgw3dw1twhd71c0000gn/T/pip-install-kid3mp55/base-api/baseapi/apis/graphql.py", line 1, in <module>
        import requests
    ModuleNotFoundError: No module named 'requests'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by furious-luke** [comment]
@AdamDonna That looks to me like you may have an old version of baseapi. I'd try clearing your virtualenv and installing again (also try pycrime version 0.0.6 instead of 0.0.5).
