### ISSUE TITLE
Install issue with BaseAPI dependency 

### ISSUE THREAD

**Issue by AdamDonna** [furious-luke/pycrime#2]
Similar to the issue with https://github.com/furious-luke/pycrime/issues/1 but with the `requests` package which is in BaseAPI

```
    ERROR: Command errored out with exit status 1:
     command: /Users/adamdonaghy/Projects/Work/expensecheck/spence/venv/bin/python3.6 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/r_/zld3tvk55kzgw3dw1twhd71c0000gn/T/pip-install-kid3mp55/base-api/setup.py'"'"'; __file__='"'"'/private/var/folders/r_/zld3tvk55kzgw3dw1twhd71c0000gn/T/pip-install-kid3mp55/base-api/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/r_/zld3tvk55kzgw3dw1twhd71c0000gn/T/pip-install-kid3mp55/base-api/pip-egg-info
         cwd: /private/var/folders/r_/zld3tvk55kzgw3dw1twhd71c0000gn/T/pip-install-kid3mp55/base-api/
    Complete output (13 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/r_/zld3tvk55kzgw3dw1twhd71c0000gn/T/pip-install-kid3mp55/base-api/setup.py", line 2, in <module>
        from baseapi import __version__
      File "/private/var/folders/r_/zld3tvk55kzgw3dw1twhd71c0000gn/T/pip-install-kid3mp55/base-api/baseapi/__init__.py", line 1, in <module>
        from .client import Client  # noqa
      File "/private/var/folders/r_/zld3tvk55kzgw3dw1twhd71c0000gn/T/pip-install-kid3mp55/base-api/baseapi/client.py", line 3, in <module>
        from .apis import Api
      File "/private/var/folders/r_/zld3tvk55kzgw3dw1twhd71c0000gn/T/pip-install-kid3mp55/base-api/baseapi/apis/__init__.py", line 2, in <module>
        from .graphql import GraphqlApi  # noqa
      File "/private/var/folders/r_/zld3tvk55kzgw3dw1twhd71c0000gn/T/pip-install-kid3mp55/base-api/baseapi/apis/graphql.py", line 1, in <module>
        import requests
    ModuleNotFoundError: No module named 'requests'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by AdamDonna** [comment]
UPDATE: Fixed if you install requests normally then install `PyCrime`
